/**
 * Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
 * SPDX-License-Identifier: MIT
 */

export enum WorkflowNodeType {
  Start = "start",
  End = "end",
  LLM = "llm",
  MCP = "mcp",
  EmbeddedScanSerialPorts = "embedded_scan_serial_ports",
  EmbeddedOpenSerial = "embedded_open_serial",
  EmbeddedCloseDevice = "embedded_close_device",
  EmbeddedResetDevice = "embedded_reset_device",
  EmbeddedGetDeviceInfo = "embedded_get_device_info",
  EmbeddedFlashFirmware = "embedded_flash_firmware",
  EmbeddedSerialWriteText = "embedded_serial_write_text",
  EmbeddedSerialWriteBytes = "embedded_serial_write_bytes",
  EmbeddedSerialReadLine = "embedded_serial_read_line",
  EmbeddedSerialExpectText = "embedded_serial_expect_text",
  EmbeddedSerialRequestResponse = "embedded_serial_request_response",
  EmbeddedGpioSetMode = "embedded_gpio_set_mode",
  EmbeddedGpioWrite = "embedded_gpio_write",
  EmbeddedGpioRead = "embedded_gpio_read",
  EmbeddedAnalogRead = "embedded_analog_read",
  EmbeddedPwmWrite = "embedded_pwm_write",
  EmbeddedServoWriteAngle = "embedded_servo_write_angle",
  EmbeddedI2cScan = "embedded_i2c_scan",
  EmbeddedI2cWriteRegister = "embedded_i2c_write_register",
  EmbeddedI2cReadRegister = "embedded_i2c_read_register",
  EmbeddedDelayMs = "embedded_delay_ms",
  EmbeddedSaveSerialLog = "embedded_save_serial_log",
  HTTP = "http",
  Code = "code",
  Lua = "lua",
  Variable = "variable",
  Condition = "condition",
  MultiCondition = "multi-condition",
  Loop = "loop",
  BlockStart = "block-start",
  BlockEnd = "block-end",
  Comment = "comment",
  Continue = "continue",
  Break = "break",
  // 应用工作流专用节点
  Agent = "agent",
  Wait = "wait",
  Webhook = "webhook",
  Vision = "vision",
  Speech = "speech",
  DeviceControl = "device_control",
  SmartHome = "smart_home",
  PhoneCamera = "phone_camera",
}
